;this file for FamiTone2 library generated by text2data tool

Bonetrousle_simplified_music_data:
	db 1
	dw @instruments
	dw @samples-3
	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	db $30 ;instrument $00
	dw @env1,@env0,@env0
	db $00
	db $30 ;instrument $01
	dw @env1,@env0,@env0
	db $00
	db $f0 ;instrument $02
	dw @env2,@env0,@env0
	db $00
	db $70 ;instrument $03
	dw @env3,@env0,@env0
	db $00
	db $30 ;instrument $04
	dw @env4,@env0,@env0
	db $00

@samples:
	db $00+<(FT_DPCM_PTR),$00,$00	;1
	db $00+<(FT_DPCM_PTR),$00,$00	;2
	db $00+<(FT_DPCM_PTR),$00,$00	;3
	db $00+<(FT_DPCM_PTR),$00,$00	;4
	db $00+<(FT_DPCM_PTR),$00,$00	;5
	db $00+<(FT_DPCM_PTR),$00,$00	;6
	db $00+<(FT_DPCM_PTR),$00,$00	;7
	db $00+<(FT_DPCM_PTR),$00,$00	;8
	db $00+<(FT_DPCM_PTR),$00,$00	;9
	db $00+<(FT_DPCM_PTR),$00,$00	;10
	db $00+<(FT_DPCM_PTR),$00,$00	;11
	db $00+<(FT_DPCM_PTR),$00,$00	;12
	db $00+<(FT_DPCM_PTR),$00,$00	;13
	db $00+<(FT_DPCM_PTR),$00,$00	;14
	db $00+<(FT_DPCM_PTR),$00,$00	;15
	db $00+<(FT_DPCM_PTR),$00,$00	;16
	db $00+<(FT_DPCM_PTR),$00,$00	;17
	db $00+<(FT_DPCM_PTR),$00,$00	;18
	db $00+<(FT_DPCM_PTR),$00,$00	;19
	db $00+<(FT_DPCM_PTR),$00,$00	;20
	db $00+<(FT_DPCM_PTR),$00,$00	;21
	db $00+<(FT_DPCM_PTR),$00,$00	;22
	db $00+<(FT_DPCM_PTR),$00,$00	;23
	db $00+<(FT_DPCM_PTR),$00,$00	;24
	db $00+<(FT_DPCM_PTR),$0c,$0f	;25
	db $00+<(FT_DPCM_PTR),$00,$00	;26
	db $00+<(FT_DPCM_PTR),$00,$00	;27
	db $00+<(FT_DPCM_PTR),$00,$00	;28
	db $00+<(FT_DPCM_PTR),$00,$00	;29
	db $00+<(FT_DPCM_PTR),$00,$00	;30
	db $00+<(FT_DPCM_PTR),$00,$00	;31
	db $00+<(FT_DPCM_PTR),$00,$00	;32
	db $00+<(FT_DPCM_PTR),$00,$00	;33
	db $00+<(FT_DPCM_PTR),$00,$00	;34
	db $00+<(FT_DPCM_PTR),$00,$00	;35
	db $00+<(FT_DPCM_PTR),$00,$00	;36
	db $00+<(FT_DPCM_PTR),$00,$00	;37
	db $00+<(FT_DPCM_PTR),$00,$00	;38
	db $00+<(FT_DPCM_PTR),$00,$00	;39
	db $00+<(FT_DPCM_PTR),$00,$00	;40
	db $00+<(FT_DPCM_PTR),$00,$00	;41
	db $00+<(FT_DPCM_PTR),$00,$00	;42
	db $00+<(FT_DPCM_PTR),$00,$00	;43
	db $00+<(FT_DPCM_PTR),$00,$00	;44
	db $00+<(FT_DPCM_PTR),$00,$00	;45
	db $00+<(FT_DPCM_PTR),$00,$00	;46
	db $00+<(FT_DPCM_PTR),$00,$00	;47
	db $00+<(FT_DPCM_PTR),$00,$00	;48
	db $00+<(FT_DPCM_PTR),$00,$00	;49
	db $00+<(FT_DPCM_PTR),$00,$00	;50
	db $00+<(FT_DPCM_PTR),$00,$00	;51
	db $00+<(FT_DPCM_PTR),$00,$00	;52
	db $00+<(FT_DPCM_PTR),$00,$00	;53
	db $00+<(FT_DPCM_PTR),$00,$00	;54
	db $00+<(FT_DPCM_PTR),$00,$00	;55
	db $00+<(FT_DPCM_PTR),$00,$00	;56
	db $00+<(FT_DPCM_PTR),$00,$00	;57
	db $00+<(FT_DPCM_PTR),$00,$00	;58
	db $00+<(FT_DPCM_PTR),$00,$00	;59
	db $00+<(FT_DPCM_PTR),$00,$00	;60
	db $00+<(FT_DPCM_PTR),$00,$00	;61
	db $00+<(FT_DPCM_PTR),$00,$00	;62
	db $00+<(FT_DPCM_PTR),$00,$00	;63

@env0:
	db $c0,$00,$00
@env1:
	db $ca,$c7,$c5,$c4,$c3,$c2,$c0,$00,$06
@env2:
	db $cf,$06,$c0,$00,$02
@env3:
	db $cb,$c7,$c4,$c2,$c1,$c0,$00,$05
@env4:
	db $cf,$00,$00


@song0ch0:
	db $fb,$06
@song0ch0loop:
@ref0:
	db $bf
@ref1:
	db $bf
@ref2:
	db $83,$88,$32,$00,$40,$00,$4a,$00,$50,$85,$4a,$85,$48,$00,$4a,$00
	db $4e,$85,$4a,$00,$40,$00,$38,$00,$32,$00
@ref3:
	db $36,$00,$38,$00,$3e,$85,$40,$00,$38,$00,$32,$00,$2c,$00,$30,$00
	db $32,$00,$36,$85,$33,$00,$89
@ref4:
	db $83,$32,$00,$40,$00,$4a,$00,$50,$83,$5c,$5e,$85,$5c,$00,$58,$00
	db $5c,$85,$5e,$00,$58,$00,$50,$00,$4a,$00
@ref5:
	db $48,$00,$4a,$00,$4e,$85,$50,$00,$4a,$00,$40,$00,$32,$00,$48,$00
	db $44,$00,$48,$85,$4a,$00,$8b
	db $fd
	dw @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref6:
	db $83,$86,$28,$85,$26,$85,$28,$85,$26,$85,$28,$85,$26,$85,$28,$85
	db $26,$81
@ref7:
	db $83,$28,$85,$26,$85,$28,$85,$26,$85,$28,$85,$26,$85,$28,$85,$26
	db $81
	db $ff,$11
	dw @ref7
	db $ff,$11
	dw @ref7
	db $ff,$11
	dw @ref7
	db $ff,$11
	dw @ref7
	db $fd
	dw @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref12:
	db $84,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a
	db $85
@ref13:
	db $1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85
	db $ff,$10
	dw @ref13
	db $ff,$10
	dw @ref13
	db $ff,$10
	dw @ref13
	db $ff,$10
	dw @ref13
	db $fd
	dw @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref18:
	db $8b,$82,$1a,$85,$1a,$95,$1a,$85,$1a,$89
@ref19:
	db $8b,$1a,$85,$1a,$95,$1a,$85,$1a,$89
	db $ff,$09
	dw @ref19
	db $ff,$09
	dw @ref19
	db $ff,$09
	dw @ref19
	db $ff,$09
	dw @ref19
	db $fd
	dw @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref24:
	db $32,$85,$32,$85,$32,$85,$33,$33,$32,$85,$32,$85,$32,$85,$33,$32
	db $81
	db $ff,$11
	dw @ref24
	db $ff,$11
	dw @ref24
	db $ff,$11
	dw @ref24
	db $ff,$11
	dw @ref24
	db $ff,$11
	dw @ref24
	db $fd
	dw @song0ch4loop
