;this file for FamiTone2 library generated by text2data tool

SmellLikeTeenSpirit_music_data:
	db 1
	dw @instruments
	dw @samples-3
	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,466,389

@instruments:
	db $70 ;instrument $00
	dw @env1,@env0,@env0
	db $00
	db $70 ;instrument $01
	dw @env2,@env0,@env0
	db $00
	db $30 ;instrument $02
	dw @env3,@env0,@env0
	db $00
	db $30 ;instrument $03
	dw @env4,@env0,@env0
	db $00

@samples:
@env0:
	db $c0,$00,$00
@env1:
	db $cd,$cb,$c9,$c8,$c7,$c5,$c4,$00,$06
@env2:
	db $cf,$06,$c0,$00,$02
@env3:
	db $c3,$c5,$c6,$c5,$c4,$c3,$c1,$c0,$00,$07
@env4:
	db $cf,$cb,$c6,$c2,$c0,$00,$04


@song0ch0:
	db $fb,$06
@song0ch0loop:
@ref0:
	db $80,$24,$89,$25,$25,$00,$91,$2e,$85,$2e,$85,$2c,$85,$2a,$89,$2b
	db $2a,$85,$00,$8d,$34,$85,$34,$85,$34,$85
	db $fd
	dw @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref1:
	db $80,$32,$89,$33,$33,$00,$91,$3c,$85,$3c,$85,$36,$85,$38,$89,$39
	db $38,$85,$00,$8d,$42,$85,$42,$85,$42,$85
	db $fd
	dw @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref2:
	db $82,$0c,$87,$00,$0c,$00,$0c,$8d,$01,$16,$00,$16,$00,$16,$00,$16
	db $85,$1a,$85,$12,$85,$01,$12,$00,$12,$8d,$01,$1c,$00,$1c,$00,$1c
	db $00,$1c,$8d
	db $fd
	dw @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref3:
	db $86,$20,$89,$21,$10,$85,$84,$1f,$1f,$1f,$1f,$86,$21,$21,$10,$85
	db $20,$85,$20,$89,$21,$10,$85,$84,$1f,$1f,$1f,$1f,$86,$21,$21,$10
	db $85,$20,$85
	db $fd
	dw @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref4:
	db $f9,$85
	db $fd
	dw @song0ch4loop
